import Button from 'or-button'
import React from 'react'

import './styles.global.scss'
import styles from './styles.scss'

class Title extends React.Component<{}, {}> {
  render() {
    return (
      <div className={styles.title}>
        <div>
          <span>Generated by: </span>
          <span className={styles['font-bold']}>foryuki/template-parcel-ts</span>
        </div>
        <Button type="primary" classname={styles.btn}>Click It</Button>
      </div>
    )
  }
}

export default Title
